version: '3.9'
services:
  app:
    build: .
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - TWITCH_CLIENT_ID=h0zgudvlf56ii2q4wpusij14t7dh3j
      - TWITCH_CLIENT_SECRET=qs9jbcscqxmafrjl03vimllcnjljbb
      - CORS_ORIGIN=http://localhost:5173,http://player-stats.local:8080
      - DB_HOST=db
      - DB_USER=statsuser
      - DB_PASSWORD=statspassword1234
      - DB_NAME=player_stats
      - DB_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword1234
      - MYSQL_DATABASE=player_stats
      - MYSQL_USER=statsuser
      - MYSQL_PASSWORD=statspassword1234
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
